# Generated by Django 3.1.6 on 2021-02-05 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proof',
            name='work',
        ),
        migrations.AlterField(
            model_name='work',
            name='images',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.proof'),
        ),
    ]
