# Generated by Django 3.1.6 on 2021-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210205_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workimage',
            name='img',
            field=models.ImageField(upload_to='photos/%Y'),
        ),
    ]
