# Generated by Django 3.1.6 on 2021-02-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_skill_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='opinion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
