# Generated by Django 3.1.6 on 2021-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210210_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='opinion',
            field=models.CharField(blank=True, default='default', max_length=50),
            preserve_default=False,
        ),
    ]
