# Generated by Django 3.1.6 on 2021-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210210_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='knowledge',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=3),
        ),
    ]
