# Generated by Django 3.1.6 on 2021-02-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='image_list',
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='work',
            name='skills',
        ),
        migrations.AddField(
            model_name='work',
            name='skills',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
    ]
