# Generated by Django 3.1.6 on 2021-02-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210205_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('work', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.work')),
            ],
        ),
    ]
