# Generated by Django 3.1.6 on 2021-02-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210205_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='images',
        ),
        migrations.DeleteModel(
            name='Proof',
        ),
        migrations.AddField(
            model_name='workimage',
            name='work',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.work'),
        ),
    ]
