# Generated by Django 3.1.6 on 2021-02-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='knowledge',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=3, max_length=3),
        ),
    ]
