export const FETCH_WORKS = 'WORKS/GET_WORKS';
export const FETCH_RECENT_WORKS = 'WORKS/GET_RECENT_WORKS'
export const FETCH_SMALL_IMAGES = 'WORKS/GET_SMALL_IMAGES';
export const FETCH_MID_IMAGES = 'WORKS/GET_MID_IMAGES';
export const FETCH_BIG_IMAGES = 'WORKS/GET_BIG_IMAGES';
export const FETCH_PREVIEW_IMAGES = 'WORKS/GET_PREVIEW_IMAGES';


export const FETCH_ALL_SKILLS = 'SKILLS/GET_ALL_SKILLS';
export const SET_SKILL_SELECTED = 'SKILLS/SET_SKILL_SELECTED';
export const UNSET_SKILL_SELECTED = 'SKILLS/UNSET_SKILL_SELECTED';

export const FETCH_WORK_DETAILS = 'WORK/FETCH_WORK_DETAILS';
export const FETCH_WORK_IMAGES = 'WORK/FETCH_WORK_IMAGES';
export const CLEAR_WORK_DETAILS = 'WORK/CLEAR_WORK_DETAILS';